var wave_questions={"wave_1": {
	    "H1DA_DailyActivity":{
	    	"H1DA1":"During the past week, how many times did you do work around the house, such as cleaning, cooking, laundry, yardwork, or caring for a pet?",
			"H1DA2":"During the past week, how many times did you do hobbies, such as collecting baseball cards, playing a musical instrument, reading, or doing arts and crafts?",
			"H1DA3":"During the past week, how many times did you watch television or videos, or play video games?",
			"H1DA4":"During the past week, how many times did you go roller-blading, roller-skating, skate-boarding, or bicycling?",
			"H1DA5":"During the past week, how many times did you play an active sport, such as baseball, softball, basketball, soccer, swimming, or football?",
			"H1DA6":"During the past week, how many times did you do exercise, such as jogging, walking, karate, jumping rope, gymnastics or dancing?",
			"H1DA7":"During the past week, how many times did you just hang out with friends?",
			"H1DA8":"How many hours a week do you watch television?",
			"H1DA9":"How many hours a week do you watch videos?",
			"H1DA10":"How many hours a week do you play video or computer games?",
			"H1DA11":"How many hours a week do you listen to the radio?"
		},
		"H1GH_GeneralHealth":{
			"H1GH1":"In general, how is your health? Would you say...",
			"H1GH2":"How often have you had a headache?",
			"H1GH3":"feeling hot all over suddenly, for no reason",
			"H1GH4":"a stomach ache or an upset stomach",
			"H1GH5":"cold sweats",
			"H1GH6":"feeling physically weak, for no reason",
			"H1GH7":"a sore throat or a cough",
			"H1GH8":"feeling very tired, for no reason",
			"H1GH9":"painful or very frequent urination (or peeing)",
			"H1GH10":"feeling really sick",
			"H1GH11":"waking up feeling tired",
			"H1GH12":"skin problems, such as itching or pimples",
			"H1GH13":"dizziness",
			"H1GH14":"chest pains",
			"H1GH15":"aches, pains, or soreness in your muscles or joints",
			"H1GH17":"poor appetite",
			"H1GH18":"trouble falling asleep or staying asleep",
			"H1GH19":"trouble relaxing",
			"H1GH20":"moodiness",
			"H1GH21":"frequent crying",
			"H1GH22":"fearfulness",
			"H1GH24":"When did you last have a physical examination by a doctor or nurse?",
			"H1GH25":"When did you last have a dental examination by a dentist or hygienist?",
			"H1GH26":"Has there been any time over the past year when you thought you should get medical care, but you did not?",
			"H1GH28":"How do you think of yourself in terms of weight?",
			"H1GH29":"Are you trying to lose weight, gain weight, or stay the same weight?",
			"H1GH32":"How often did you drink milk, or eat yogurt, or cheese yesterday?",
			"H1GH33":"How often did you eat fruit or drink fruit juice yesterday?",
			"H1GH34":"How often did you eat vegetables yesterday?",
			"H1GH35":"How often did you eat bread, cereal, pretzels, rice, or pasta yesterday?",
			"H1GH36":"How often did you eat cookies, doughnuts, pie, or cake yesterday?"
		},
		"H1HS_AccessToHealthServices":{
			"H1HS1":"In the past year have you had a routine physical examination?",
			"H1HS3":"In the past year, have you received psychological or emotional counseling?",
			"H1HS7":"In the past year, have you received family planning counseling or services?",
		},
		"H1TO_TobaccoAlcoholDrugs":{
			"H1TO1":"Have you ever tried cigarette smoking, even just 1 or 2 puffs?",
			"H1TO12":"Have you ever smoked cigarettes regularly, that is, at least 1 cigarette every day for 30 days?",
			"H1TO50":"Are cigarettes easily available to you in your home?",
			"H1TO51":"Is alcohol easily available to you in your home?",
		},
		"H1FS_FeelingScale":{
			"H1FS1":"You were bothered by things that usually don’t bother you.",
			"H1FS3":"You felt that you could not shake off the blues, even with help from your family and your friends.",
			"H1FS4":"You felt that you were just as good as other people.",
			"H1FS5":"You had trouble keeping your mind on what you were doing.",
			"H1FS6":"You felt depressed.",
			"H1FS7":"You felt that you were too tired to do things.",
			"H1FS8":"You felt hopeful about the future.",
			"H1FS9":"You thought your life had been a failure.",
			"H1FS10":"You felt fearful.",
			"H1FS11":"You were happy",
			"H1FS12":"You talked less than usual.",
			"H1FS13":"You felt lonely.",
			"H1FS14":"People were unfriendly to you.",
			"H1FS15":"You enjoyed life.",
			"H1FS16":"You felt sad.",
			"H1FS17":"You felt that people disliked you.",
			"H1FS18":"It was hard to get started doing things.",
			"H1FS19":"You felt life was not worth living."
		}
	},

	"wave_2": {
		 "H2DA_DailyActivity":{
	    	"H2DA1":"work around the house, such as cleaning, cooking, doing laundry, doing yardwork, or caring for a pet?",
			"H2DA2":"do hobbies, such as collecting baseball cards, playing a musical instrument, reading, or doing arts and crafts?",
			"H2DA3":"watch television or videos, or play video games?",
			"H1DA4":"go roller-blading, roller-skating, skate-boarding, or bicycling?",
			"H2DA5":"play an active sport, such as baseball, softball, basketball, soccer,swimming, or football?",
			"H2DA6":"exercise, such as jogging, walking, doing karate, jumping rope, doing gymnastics or dancing?",
			"H2DA7":"how many times did you just hang out with friends?",
			"H2DA8":"How many hours a week do you watch television?",
			"H2DA9":"How many hours a week do you watch videos?",
			"H2DA10":"How many hours a week do you play video or computer games?",
			"H2DA11":"How many hours a week do you listen to the radio?"
		},
		"H2GH_GeneralHealth":{
			"H2GH1":"In general, how is your health? Would you say...",
			"H2GH2":"do you have any limitations attending school or in your ability to do regular work?",
			"H2GH3":"do you have difficulty in doing regular household chores, shopping, or errands?",
			"H2GH4":"do you have limitations in doing strenuous activities such as running, swimming, or other sports?",
			"H2GH5":"do you have difficulty with personal care or hygiene, namely bathing,dressing, eating, or using the toilet?",
			"H2GH8":"How often have you had a headache?",
			"H2GH9":"feeling hot all over suddenly, for no reason",
			"H2GH10":"a stomach ache or an upset stomach",
			"H2GH11":"cold sweats",
			"H2GH12":"feeling physically weak, for no reason",
			"H2GH13":"had a sore throat or a cough?",
			"H2GH14":"felt very tired, for no reason?",
			"H2GH15":"painful or very frequent urination (or peeing)",
			"H2GH16":"feeling really sick",
			"H2GH17":"waking up feeling tired",
			"H2GH18":"skin problems, such as itching or pimples",
			"H2GH19":"dizziness",
			"H2GH20":"chest pains",
			"H2GH21":"aches, pains, or soreness in your muscles or joints",
			"H2GH22":"poor appetite",
			"H2GH23":"trouble falling asleep or staying asleep",
			"H2GH24":"trouble relaxing",
			"H2GH25":"been moody?",
			"H2GH26":"frequent crying",
			"H2GH27":"been afraid?",
			"H2GH28":"Has there been any time over the past year when you thought you should get medical care, but you did not?"
		},
		"H2HS_AccessToHealthServices":{
			"H2HS1":"In the past year have you had a routine physical examination?",
			"H2HS3":"In the past year have you had a dental examination by a dentist or hygienist?",
			"H2HS7":"In the past year have you attended a drug abuse or alcohol abuse treatment program?",
			"H2HS9":"In the past year have you received family planning counseling or services?"
		},
		"H2TO_TobaccoAlcoholDrugs":{
			"H2TO1":"Have you ever tried cigarette smoking, even just 1 or 2 puffs?",
			"H2TO10":"Of your three best friends, how many smoke at least one cigarette a day?",
			"H2TO11":"Are cigarettes easily available to you in your home?",
			"H2TO15":"have you had a drink of beer, wine, or liquor—not just a sip or a taste of someone else’s drink—more than two or three times?",
			"H2TO41":"Of your three best friends, how many drink alcohol at least once a month?",
			"H2TO42":"Is alcohol easily available to you in your home?",
			"H2TO44":"have you tried or used marijuana?",
			"H2TO48":"Of your three best friends, how many use marijuana at least once a month?"
		},
		"H2FS_FeelingScale":{
			"H2FS1":"You were bothered by things that usually don’t bother you.",
			"H2FS3":"You felt that you could not shake off the blues, even with help from your family and your friends.",
			"H2FS4":"You felt that you were just as good as other people.",
			"H2FS5":"You had trouble keeping your mind on what you were doing.",
			"H2FS6":"You felt depressed.",
			"H2FS7":"You felt that you were too tired to do things.",
			"H2FS8":"You felt hopeful about the future.",
			"H2FS9":"You thought your life had been a failure.",
			"H2FS10":"You felt fearful.",
			"H2FS11":"You were happy",
			"H2FS12":"You talked less than usual.",
			"H2FS13":"You felt lonely.",
			"H2FS14":"People were unfriendly to you.",
			"H2FS15":"You enjoyed life.",
			"H2FS16":"You felt sad.",
			"H2FS17":"You felt that people disliked you.",
			"H2FS18":"It was hard to get started doing things.",
			"H2FS19":"You felt life was not worth living."
		},
		"H2NU_Nutrition":{
			"H2NU1":"Did you drink milk, including milk poured on cereal or dessert?",
			"H2NU3":"Did you drink soft drinks or mixers, such as tonic water or club soda, etc.?",
			"H2NU6":"Did you drink other 100% fruit juice, not including fruit-flavored drinks?",
			"H2NU7":"Did you drink Koolaid, fruit-flavored drinks, Gatoraid, or other sport drinks?",
			"H2NU9":"Did you drink water?",
			"H2NU10":"apples, applesauce, pears, or pineapple?",
			"H2NU11":"bananas, plantains, grapes, berries, or cherries?",
			"H2NU12":"cantaloupes, melons, mangoes, or papayas?",
			"H2NU13":"oranges, grapefruit, tangerines, or kiwis?"
		}

	},

	"wave_3": {
		"H3DA_DailyActivity":{
	    	"H3DA1":"In the past seven days, how m any times did you do housework, such as cleaning, cooking, or laundry?",
			"H3DA2":"In the past seven days, how many times did you engage in a hobby such as working on a collection, playing cards or board games, arts and crafts, drama, playin g a musical instrument or singing with a group, or shopping just for fun?",
			"H3DA3":"In the past seven days, how many times did you watch a movie, play video or computer games, or use a computer for surfing the Web, exchanging email, or participating in a chat room?",
			"H3DA4":"On the average, how many hours a week do you spend watching videos?",
			"H3DA5":"On the average, how many hours a week do you spend playing video or computer games, or using a computer for something other than school work?",
			"H3DA6":"In the past seven days, how many times did you watch television?",
			"H3DA7":"On the average, how many hours a week do you spend watching television?",
			"H3DA8":"In the past seven days, how many times did you bicycle, skateboard, dance, hike, hunt, or do yard work?",
			"H3DA11":"In the past seven days, how many times did you participate in individual sports such as running, wrestling, swimming, cross-country skiing, cycle racing, or martial arts?",
			"H3DA12":"In the past seven days, how many times did you participate in gymnastics, weight lifting, or strength training?",
			"H3DA13":"In the past seven days, how many times did you play golf, go fishing or bowling, or play softball or baseball?",
			"H3DA14":"In the past seven days, how many times did you walk for exercise?",
			"H3DA15":"In the past seven days, how many times did you just “hang out” with friends , or talk on the telephone for mo re th an five minutes?",
			"H3DA16":"Were the past seven days typical in terms of your physical activity?",
			"H3DA17":"Are you generally more active or less active than you were last week?",
			"H3DA19":"How many children between the ages of six and twelve live in your household?",
			"H3DA20":"On the average, how many hours per week do you spend taking care of the children in your household who are less than six years old by feeding, bathing, or dressing them?",
			"H3DA22":"Are the children in your household involved in any sports activities?",
			"H3DA23":"In the last seven days did you attend any of their sports activities as a spectator or transport any of them to a game or practice?",
			"H3DA25":"In the last seven days did you actively participate in any of their sports activities—for example as a coach or referee?",
			"H3DA28":"Do you currently have a job?"
		},
		"H3GH_GeneralHealth":{
			"H3GH1":"In general, how is your health? Would you say...",
			"H3GH2":"How do you think of yourself in terms of weight?",
			"H3GH3":"What are you currently doin g about you r weight? Are you trying to lose weight, gain weight or bulk up, or stay the same weight—or are you not trying to do anyth ing about your weight?",
			"H3GH5":"In the past seven days, how many times did you go to an exercise or fitness center to exercise or work out?",
			"H3GH6":"In the past seven days, have you eaten so much in a short period that you would have been embarrassed if others had see you do it?",
			"H3GH7":"In the past seven days, have you been afraid to start eating because you thought you wouldn’t be able to stop or control your eating?",
			"H3GH8":"Have you ever been told by a doctor that you have an eating disorder, such as anorexia nervosa or bulimia?",
			"H3GH15":"In the past seven days, how often did you fall asleep when you should have been awake (for example, during class or at work)?",
			"H3GH16":"In the past seven days, how often did you take a nap?",
			"H3GH17":"Do you consider yourself a vegetarian?",
			"H3GH18":"On how many of the past seven days did you eat food from a fastfood place, McDonalds, Kentucky Fried Chicken, Pizza Hut, Taco Bell, or a local fastfood restaurant?",
			"H3GH19":"On how many of the past seven days did you eat breakfast—that is, a meal within an hour of getting up?",
			"H3GH20":"In the last month, have you taken any vitamins or minerals?"
		},
		"H3HS_AccessToHealthServices":{
			"H3HS1":"Over the past 12 months, how many months did you have health insurance?",
			"H3HS3":"Over the past 12 months, were you offered health insurance through work or school?",
			"H3HS6":"Has there been any time in the past 12 months when you thought you should get medical care, but you did not?",
			"H3HS11":"How long ago did you last consult a doctor or nurse?"
		},
		"H3TO_TobaccoAlcoholDrugs":{
			"H3TO1":"Have you ever tried cigarette smoking, even just 1 or 2 puffs?",
			"H3TO27":"I often try new things just for fun or thrills, even if most people think they are a waste of time.",
			"H3TO28":"When nothing new is happening, I usually start looking for something exciting.",
			"H3TO29":"I can usually get people to believe me, even when what I’m saying isn’t quite true.",
			"H3TO31":"I often do things based on how I feel at the moment.",
			"H3TO32":"I sometimes get so excited that I lose control of myself.",
			"H3TO33":"I often follow my instincts, without thinking through all the details.",
			"H3TO34":"I can do a good job of “stretching the truth ” when I’m talking to people.",
			"H3TO35":"I change my interest a lot, because my attention often shifts to something else.",
			"H3TO36":"During the past 30 days, on how many days have you used chewing tobacco (such as Red Man, Levi Garrett, or Beechn ut) or snuff (such as Skoal, Skoal Band its, or Copen hagen)?",
			"H3TO37":"Since June 1995, have you had a drink of beer, wine, or liquor more than two or three times? Do not include sips or tastes from someone else’s drink.",
			"H3TO103":"Of your three best friends, how many drink alcohol at least once a month?",
			"H3TO104":"Of you r th ree best friend s, how many binge drink at least once a month?",
			"H3TO111":"Since June 1995, have you used any kind of cocaine—including crack, freebase, or powder?",
			"H3TO130":"During the past 12 months, have you ever seriously thought about committing suicide?",
			"H3TO135":"During the past 12 months, have any of your family members tried to kill them selves?"
		},
		"H3ID_Illnesses Medications Physical Disabilities":{
			"H3ID1":"vigorous activities, such as running, lifting heavy objects,participating in strenuous sports",
			"H3ID2":"moderate activities, such as moving a table, pushing a vacuum cleaner, bowling, playing golf",
			"H3ID3":"lifting or carrying a bag of groceries",
			"H3ID4":"climbing several flights of stairs",
			"H3ID5":"climbing one flight of stairs",
			"H3ID6":"bending, kneeling , or stooping",
			"H3ID7":"walking more than a mile",
			"H3ID10":"bathing and dressing your self.",
			"H3ID12":"In the past 30 days, have you taken antibiotics, such as tetracycline, doxycycline, amoxicillin, or erythromycin?",
			"H3ID13":"Have you ever been diagnosed with asthma?",
			"H3ID14":"Have you ever been diagnosed with cancer or leukemia?",
			"H3ID15":"Have you ever been diagnosed with depression?",
			"H3ID16":"Have you ever been diagnosed with diabetes?",
			"H3ID19":"Have you ever been diagnosed with epilepsy or seizure disorder?"
		},
		"H3SP_Social Psychology and Mental Health":{
			"H3SP1":"In the past 12 months, how often have you laughed a lot?",
			"H3SP2":"In the past 12 month s, how often have you cried a lot?",
			"H3SP3":"How satisfied are you with your life as a whole?",
			"H3SP4":"Compared to other people you rage, how intelligent are you?",
			"H3SP5":"You were bothered by things that usually don’t bother you.",
			"H3SP6":"You could not shake off the blues, even with help from your family and your friends, during the past seven days.",
			"H3SP7":"You felt that you were just as good as other people, during the past seven days.",
			"H3SP8":"You had trouble keeping your mind on what you were doing, during the past seven days."
		}
	},

	"wave_4": {
		"H4DA_DailyActivity":{
	    	"H4DA1":"In the past seven days, how many hours did you watch television or videos, including VHS, DVDs or music videos?",
			"H4DA2":"In the past seven days, how many times did you bicycle, skateboard, dance, hike, hunt, or do yard work",
			"H4DA3":"In the past seven days, how many times did you roller blade, roller skate, downhill ski, snow board, play racquet sports, or do aerobics?",
			"H4DA4":"In the past seven days, how many times did you participate in strenuous team sports such as football, soccer, basketball, lacrosse, rugby, field hockey, or ice hockey?",
			"H4DA5":"In the past seven days, how many times did you participate in individual sports such as running, wrestling, swimming, cross-country skiing, cycle racing, or martial arts?",
			"H4DA6":"In the past seven days, how many times did you participate in gymnastics, weight lifting, or strength training?",
			"H4DA7":"In the past seven days, how many times did you play golf, go fishing or bowling, or play softball or baseball?",
			"H4DA8":"In the past seven days, how many times did you walk for exercise?",
			"H4DA9":"Were the past seven days typical in terms of your physical activity?",
			"H4DA10":"Are you generally more active or less active than you were in the past seven days?",
			"H4DA11":"In the past 24 hours, have you participated in vigorous physical activity long enough to work up a sweat, get your heart thumping, or get out of breath?"
		},
		"H4GH_GeneralHealth":{
			"H4GH1":"In general, how is your health?",
			"H4GH2":"In the past 30 days, how often did a health problem cause you to miss a day of school or work?",
			"H4GH6":"What is your current weight in pounds?",
			"H4GH7":"How do you think of yourself in terms of weight?",
			"H4GH8":"On how many of the past seven days did you eat food from a fastfood place, McDonalds, Kentucky Fried Chicken, Pizza Hut, Taco Bell, or a local fastfood restaurant?",
			"H4GH9":"In the past 7 days, how many regular (non-diet) sweetened drinks did you have? Include regular soda, juice drinks, sweetened tea or coffee, energy drinks, flavored water, or other sweetened drinks."
		},
		"H4HS_AccessToHealthServices":{
			"H4HS1":"Which of the following best describes your current health insurance situation?",
			"H4HS4":"Has there been any time in the past 12 months when you thought you should get medical care, but you did not?",
			"H4HS5":"In the past 12 months, did a health problem get worse because you did not get care when you thought you should?"
		},
		"H4TO_TobaccoAlcoholDrugs":{
			"H4TO1":"Have you ever smoked an entire cigarette?",
			"H4TO5":"During the past 30 days, on how many days did you smoke cigarettes?",
			"H4TO23":"Have you smoked a cigar or pipe at least 20 times in your entire life?",
			"H4TO25":"During the past 30 days, on how many days have you used chewing tobacco (such as Red Man, Levi Garrett, or Beechn ut) or snuff (such as Skoal, Skoal Band its, or Copen hagen)?",
			"H4TO33":"Since June 1995, have you had a drink of beer, wine, or liquor more than two or three times? Do not include sips or tastes from someone else’s drink."	
				
		}
	}
}